package dev.aperture.editor.model.command;
import dev.aperture.editor.model.history.*;
import dev.aperture.editor.model.read.*;
import dev.aperture.parameter.ParameterValue;
import dev.aperture.runtime.model.command.ArchitecturalCommand;
import java.time.Instant;
import java.util.*;
public final class DefaultEditorCommandGateway implements EditorCommandGateway {
	private final EditorCommandTransport transport;private final DiagnosticsModel diagnostics;private final RuntimeActionResolver runtimeActions;private final EditorReadModel read;private final HistoryProjection history;
	private final Map<UUID,PendingAction> pending=new HashMap<>();
	public DefaultEditorCommandGateway(EditorCommandTransport transport,DiagnosticsModel diagnostics){this(transport,diagnostics,new StandardRuntimeActionResolver(),null,null);}
	public DefaultEditorCommandGateway(EditorCommandTransport transport,DiagnosticsModel diagnostics,RuntimeActionResolver resolver){this(transport,diagnostics,resolver,null,null);}
	public DefaultEditorCommandGateway(EditorCommandTransport transport,DiagnosticsModel diagnostics,RuntimeActionResolver resolver,EditorReadModel read,HistoryProjection history){this.transport=Objects.requireNonNull(transport);this.diagnostics=Objects.requireNonNull(diagnostics);this.runtimeActions=Objects.requireNonNull(resolver);this.read=read;this.history=history;transport.addResultListener(this::onResult);}
	public EditorCommandSubmission submit(ArchitecturalCommand command){return submit(command,new ExpectedRevision(0,0));}
	public EditorCommandSubmission submit(ArchitecturalCommand command,ExpectedRevision revision){return dispatch(UUID.randomUUID(),command,revision,Operation.EDIT,null,null);}
	public EditorCommandSubmission submitRuntimeAction(dev.aperture.runtime.model.object.ArchitecturalObjectId id,String actionId,ExpectedRevision revision){return dispatch(UUID.randomUUID(),runtimeActions.resolve(id,actionId),revision,Operation.RUNTIME,null,null);}
	public EditorCommandSubmission submitParameterEdit(dev.aperture.runtime.model.object.ArchitecturalObjectId id,String key,ParameterValue before,ParameterValue after,ExpectedRevision revision){return dispatch(UUID.randomUUID(),new SetParameterArchitecturalCommand(id,key,after),revision,Operation.EDIT,null,before);}
	public EditorCommandSubmission undo(EditorHistoryEntry entry){return entry==null||!entry.undoable()||entry.compensation()==null?rejected("History entry is not undoable",entry):dispatch(UUID.randomUUID(),entry.compensation().get(),entry.expectedRevision(),Operation.UNDO,entry,null);}
	public EditorCommandSubmission redo(EditorHistoryEntry entry){return entry==null||entry.repetition()==null?rejected("History entry is not redoable",entry):dispatch(UUID.randomUUID(),entry.repetition().get(),entry.expectedRevision(),Operation.REDO,entry,null);}
	public EditorCommandSubmission undo(HistoryProjection projection){UUID id=UUID.randomUUID();var entry=projection.beginUndo(id);if(entry.isEmpty())return rejected("No undoable history entry",null);return dispatch(id,entry.get().compensation().get(),entry.get().expectedRevision(),Operation.UNDO,entry.get(),null);}
	public EditorCommandSubmission redo(HistoryProjection projection){UUID id=UUID.randomUUID();var entry=projection.beginRedo(id);if(entry.isEmpty())return rejected("No redoable history entry",null);return dispatch(id,entry.get().repetition().get(),entry.get().expectedRevision(),Operation.REDO,entry.get(),null);}
	private EditorCommandSubmission dispatch(UUID id,ArchitecturalCommand command,ExpectedRevision revision,Operation operation,EditorHistoryEntry source,ParameterValue explicitBefore){
		PendingAction action=new PendingAction(command,revision,operation,source,explicitBefore!=null?explicitBefore:before(command));pending.put(id,action);var result=transport.submit(id,command,revision);if(result.status()!=EditorCommandSubmission.Status.PENDING)onResult(result);return result;
	}
	private synchronized void onResult(EditorCommandSubmission result){var action=pending.remove(result.commandId());if(action==null)return;boolean accepted=result.status()==EditorCommandSubmission.Status.ACCEPTED;if(action.operation()==Operation.UNDO||action.operation()==Operation.REDO){if(history!=null)history.completeOperation(result.commandId(),accepted);if(!accepted)addDiagnostic(action.command(),result);return;}if(!accepted){addDiagnostic(action.command(),result);if(history!=null)history.recordRejected(entry(result,action,false));return;}if(history!=null){if(action.operation()==Operation.RUNTIME)history.recordRuntime(entry(result,action,true));else history.recordDesign(entry(result,action,true));}}
	private EditorHistoryEntry entry(EditorCommandSubmission result,PendingAction action,boolean accepted){var command=action.command();boolean parameter=command instanceof SetParameterArchitecturalCommand;java.util.function.Supplier<ArchitecturalCommand> compensation=null,repetition=null;if(parameter&&action.before()!=null){var set=(SetParameterArchitecturalCommand)command;compensation=()->new SetParameterArchitecturalCommand(set.target(),set.parameterKey(),action.before());repetition=()->set;}return new EditorHistoryEntry(result.commandId(),command.target().objectId(),command.commandType(),command.commandType(),String.valueOf(action.before()),parameter?String.valueOf(((SetParameterArchitecturalCommand)command).value()):"", "client",Instant.now(),accepted?EditorHistoryEntry.Result.ACCEPTED:EditorHistoryEntry.Result.REJECTED,result.objectRevision(),parameter,compensation,repetition,new ExpectedRevision(result.objectRevision(),result.stateRevision()));}
	private ParameterValue before(ArchitecturalCommand command){if(read==null||!(command instanceof SetParameterArchitecturalCommand set))return null;return read.object(command.target().objectId()).flatMap(view->view.parameters().get(set.parameterKey())).orElse(null);}
	private void addDiagnostic(ArchitecturalCommand command,EditorCommandSubmission result){diagnostics.add(new EditorDiagnostic(EditorDiagnostic.Severity.ERROR,result.status().name().toLowerCase(Locale.ROOT),result.message(),Optional.of(command.target().objectId()),Optional.empty(),"command",Instant.now(),result.status()==EditorCommandSubmission.Status.REVISION_CONFLICT?"Resync object":"Review command values",false));}
	private EditorCommandSubmission rejected(String message,EditorHistoryEntry entry){long revision=entry==null?0:entry.revision();long state=entry==null?0:entry.expectedRevision().stateRevision();return new EditorCommandSubmission(UUID.randomUUID(),EditorCommandSubmission.Status.REJECTED,message,revision,state);}
	private enum Operation{EDIT,RUNTIME,UNDO,REDO}private record PendingAction(ArchitecturalCommand command,ExpectedRevision revision,Operation operation,EditorHistoryEntry source,ParameterValue before){}
}