package dev.aperture.pipeline;

public enum DiagnosticCode {
	TYPE_NOT_FOUND,
	INVALID_TYPE_ID,
	PARAMETER_TYPE_MISMATCH,
	PARAMETER_OUT_OF_RANGE,
	CONSTRAINT_VIOLATION,
	COMPONENT_GRAPH_INVALID,
	GEOMETRY_COMPILATION_FAILED,
	MESH_COMPILATION_FAILED,
	CACHE_FAILURE,
	INTERNAL_ERROR
}