package dev.aperture.editor.imgui;
import dev.aperture.editor.model.inspector.*;import dev.aperture.parameter.ParameterValue;import imgui.ImGui;
final class InspectorWindow{
	private final ApertureUiContext c;private final DearImGuiPropertyEditor editor;InspectorWindow(ApertureUiContext c,DearImGuiPropertyEditor editor){this.c=c;this.editor=editor;}
	void cancelEdit(){editor.cancel();}
	void render(){if(!ImGui.begin("Inspector")){ImGui.end();return;}var s=c.session.selection().snapshot();if(s.objectIds().isEmpty())ImGui.textDisabled("No architectural object selected");else if(s.objectIds().size()>1)ImGui.text(s.objectIds().size()+" objects selected (read-only)");else c.session.readModel().object(s.primaryObject()).ifPresent(v->{ImGui.text(v.displayName());ImGui.textDisabled(v.typeId()+"  /  "+v.familyId());float[] color=v.syncStatus().name().contains("SYNC")?ApertureStyle.SUCCESS:ApertureStyle.WARNING;ImGui.textColored(color[0],color[1],color[2],1,v.syncStatus()+"   Revision "+v.objectRevision());ImGui.separator();for(InspectorSection section:c.session.inspector().sections(s.primaryObject()))if(ImGui.collapsingHeader(section.label()))for(PropertyDescriptor p:section.properties())property(s.primaryObject(),p);});ImGui.end();}
	private void property(dev.aperture.runtime.model.object.ArchitecturalObjectId id,PropertyDescriptor p){ImGui.textDisabled(p.displayName());ImGui.sameLine(ApertureStyle.LABEL_WIDTH);Object value=p.value();if(value instanceof ParameterValue parameter&&editor.render(id,p,parameter))return;ImGui.text(format(value)+(p.unit().isBlank()?"":" "+p.unit()));}
	private static String format(Object value){if(!(value instanceof ParameterValue v))return String.valueOf(value);return switch(v){case ParameterValue.LengthValue x->Double.toString(x.millimeters());case ParameterValue.AngleValue x->Double.toString(x.degrees());case ParameterValue.CountValue x->Integer.toString(x.value());case ParameterValue.NumberValue x->Double.toString(x.value());case ParameterValue.EnumValue x->x.value();case ParameterValue.BoolValue x->Boolean.toString(x.value());case ParameterValue.MaterialRefValue x->x.raw();};}
}
